### ISSUE TITLE
Error message should not give information on valid username

### ISSUE THREAD

**Issue by jbleduigou** [linto-ai/linto-platform-admin#3]
Hi,

Currently a malicious user could find valid usernames with the help of error messages.

We should maybe return a generic error message such as "Invalid username or password"

**Comment by jbleduigou** [comment]
Invalid user screenshot

![image](https://user-images.githubusercontent.com/1489214/89278773-d2264680-d646-11ea-9b72-c1634ff62c78.png)

**Comment by jbleduigou** [comment]
Invalid password screenshot 

![image](https://user-images.githubusercontent.com/1489214/89278809-dfdbcc00-d646-11ea-9cf5-5828b8401ea1.png)

**Comment by rlopezdev** [comment]
Hi @jbleduigou,
I'm sorry to answer you so late and I want to thank you for your feedbacks.
We've been working a lot on the new version of the Administration interface and your issue has been resovled on the "next" branch.
I recommand you to use the "next" branch until we publish the new version of "linto-platform-stack"
We will be posting a lot of updates, please keep in touch with us ;)

**Comment by jbleduigou** [comment]
Hi @rlopezdev,
Thanks for replying!
Do you have any estimated date for the upcoming release?
