### ISSUE TITLE
Start admin interface services ? 

### ISSUE THREAD

**Issue by dialloDioulde** [linto-ai/linto-platform-admin#5]
hello everyone, please i need help to start LinTo Admin services ? 
I did all steps defined here but i don't see the command line which allows to start the services ? 
Thanks in advance !

**Comment by damienlaine** [comment]
https://doc.linto.ai/#/stack/stack please, read thoroughly.

**Comment by dialloDioulde** [comment]
Hello thank you for your response but  so far i can't use linTon on my windows pc. 
Please if you have a little time i would like your help and this is my mail mddiallo@alteca.fr

Thanks in advance !

**Comment by damienlaine** [comment]
Windows PC ? What is that ? I asume it's a Linux distribution running on a server with Docker Swarm mode enabled as stated on the docs... *cough cough*
